TARGET = libProject.a

DEPENDENCY_FILE = .dependencies

OBJS =\
  DeleteThis.o


INCLUDE =\
 -I$(CPP_U_TEST)/include\
 -I.
 
LIBDIR = ../lib
 
include $(CPP_U_TEST)/build/StaticLibMakefile
