#ifndef CONFIG_H_
#define CONFIG_H_

#cmakedefine CPPUTEST_COMPILATION @CPPUTEST_COMPILATION@

#cmakedefine CPPUTEST_MEM_LEAK_DETECTION_DISABLED

#cmakedefine CPPUTEST_STD_C_LIB_DISABLED
#cmakedefine CPPUTEST_STD_CPP_LIB_DISABLED

#cmakedefine INCLUDE_GTEST_TESTS

#endif
