
OBJS = \
 NullTest.o \
 TestInstaller.o \
 TestOutput.o \
 CommandLineTestRunner.o\
 Failure.o\
 MemoryLeakWarningPlugin.o\
 SimpleString.o \
 SimpleStringExtensions.o \
 TestHarness_c.o \
 TestPlugin.o \
 Utest.o \
 TestRegistry.o\
 TestResult.o \
 JUnitTestOutput.o

INCLUDE =\
 -I$(CPP_U_TEST)/include/CppUTest\
 -I$(CPP_U_TEST)/include/Platforms/$(CPP_PLATFORM)\
 -I.


LIBDIR = $(CPP_U_TEST)/lib

include $(CPP_U_TEST)/build/ObjMakefile
