
OBJS =\
 CircularBuffer.o CircularBufferTest.o\
 PrinterTest.o\
 Printer.o\
 hello.o\
 HelloTest.o

INCLUDE =\
 -I../include\
 -I$(CPP_U_TEST)/include\
 -I$(CPP_U_TEST)/include/Platforms/$(CPP_PLATFORM)\
 -I.

LIBDIR = ../lib

include $(CPP_U_TEST)/build/ObjMakefile




