FROM ubuntu

RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends dosbox make openssl ca-certificates git

WORKDIR /cpputest_build

COPY ../ /cpputest

CMD ["/cpputest/scripts/dos_build_test.sh"]
