TARGET = libProject.a

DEPENDENCY_FILE = .dependencies

OBJS =\
 ProjectBuildTimeTest.o\
 ProjectBuildTime.o\

INCLUDE =\
 -I$(CPP_U_TEST)/include\
 -I.
 
LIBDIR = ../lib
 
include $(CPP_U_TEST)/build/StaticLibMakefile
