set(_CPPUTEST_BUILDTIME_DISCOVER_TESTS_DIR "${CMAKE_CURRENT_LIST_DIR}")

# Create target to discover tests
function (cpputest_buildtime_discover_tests EXECUTABLE)
  set(DISCOVER_SCRIPT "${_CPPUTEST_BUILDTIME_DISCOVER_TESTS_DIR}/CppUTestBuildTimeDiscoverTests/discover.cmake")

  add_custom_command (TARGET ${EXECUTABLE}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -DTESTS_DETAILED:BOOL=${TESTS_DETAILED} -DEXECUTABLE=$<TARGET_FILE:${EXECUTABLE}> -P ${DISCOVER_SCRIPT}
    VERBATIM
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMENT "Discovering Tests in ${EXECUTABLE}"
    VERBATIM)
endfunction ()
