---
name: Deploy Latest

"on":
  workflow_run:
    workflows: ["Basic builds"]
    branches: ["master"]
    types: ["completed"]

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.repository == 'cpputest/cpputest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/actions/download-artifact/issues/3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: basic.yml
          name: Distribution
          workflow_conclusion: success
          branch: master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-passing-build
          name: Latest passing build
          body: |
            This is the automatic release from GitHub Actions.
            Whenever a build passes, it gets released as Latest Passing Build.
          files: |
            cpputest-latest.tar.gz
            cpputest-latest.zip
          fail_on_unmatched_files: true
